### ISSUE TITLE
Add option for scrolling through results

### ISSUE THREAD

**Issue by Siddhartha-Ghai** [Krinkle/mw-tool-orphantalk#2]
As of now the only way to view later results is to increase the number of results shown. Please add an option to scroll through the results, i.e next page previous page links at the bottom. Thanks.

**Comment by Krinkle** [comment]
I don't think a stable pager can be built here as the underlying data can change at any time. It's not obvious to me how we'd avoid new results from being added to "page 1" after you've moved to "page 2".

In general, the idea for OrphanTalk is to serve as a backlog of issues, not as a list of permanently or completely browsable results. As such, I think showing a hundred (likely actionable) results should suffice.

If the tool give you more than 100 results that are not actionable, then likely there is some kind of filter that should be applied. If the filter you need doesn't exist, perhaps we can add it! I'm closing this now. Please note that as of today, new issues should be created on Phabricator instead: <https://phabricator.wikimedia.org/tag/orphantalk/>.
