### ISSUE TITLE
Missing some projects/others duplicated?

### ISSUE THREAD

**Issue by Avicennasis** [Krinkle/mw-tool-orphantalk#5]
It appears that some projects are not available? Notably scowiki and scnwiki are missing. And others have multiple entries? cewiki (2x) chwiki (3x) frwiki (3x) gawiki (3x) etc.  

The first chwiki listed seems to work fine. The second & third chwiki gives links that all give a "Bad title" error.

**Comment by Krinkle** [comment]
They are in fact different wikis, but it seems the subdomain is being trimmed for no apparent reason:

```html
<option value="cewiki" data-url="ce.wikipedia.org">ce.wikipedia.org</option>
<option value="cebwiki" data-url="ce.wikipedia.org">ce.wikipedia.org</option>
..
<option value="chwiki" data-url="ch.wikipedia.org">ch.wikipedia.org</option>
<option value="chrwiki" data-url="ch.wikipedia.org">ch.wikipedia.org</option>
<option value="chywiki" data-url="ch.wikipedia.org">ch.wikipedia.org</option>
..
<option value="ganwiki" data-url="ga.wikipedia.org">ga.wikipedia.org</option>
<option value="gagwiki" data-url="ga.wikipedia.org">ga.wikipedia.org</option>
<option value="gawiki" data-url="ga.wikipedia.org">ga.wikipedia.org</option>
```

**Comment by Krinkle** [comment]
Upstream issue: <https://phabricator.wikimedia.org/T153987>

**Comment by Krinkle** [comment]
Upstream issue is fixed. Thanks @Avicennasis for reporting!
