### ISSUE TITLE
Provide mass deletion option

### ISSUE THREAD

**Issue by BodhisattwaMandal** [Krinkle/mw-tool-orphantalk#6]
Provide option for mass deletion of orphan talks to avoid repetitive job of deleting each and every talk pages

**Comment by Krinkle** [comment]
@BodhisattwaMandal This is intentionally not done. Each entry should be reviewed with care (check the history, check the subject page and why that one was deleted.) Orphan pages are not always meant to be deleted. Sometimes they are articles created in the wrong place, or articles moved by accident, or worth keeping for historical record, and other reasons.

To prevent creation of orphan talk pages, you might want to explore other options, such as making sure "Delete talk page" is enabled by default when administrators delete pages on your wiki(s).
