### ISSUE TITLE
Tool not working

### ISSUE THREAD

**Issue by BodhisattwaMandal** [Krinkle/mw-tool-orphantalk#7]
![screenshot from 2017-08-08 19 19 02](https://user-images.githubusercontent.com/13746143/29074924-8e570a5a-7c6e-11e7-888d-34a8f69753c9.png)

**Comment by Krinkle** [comment]
Thanks for the report. This is caused by a Toolforge problem. There is unfortunately little I can do about it. The general report about this problem can be found at <https://phabricator.wikimedia.org/T166949>.
