### ISSUE TITLE
Make the tool mobile responsive

### ISSUE THREAD

**Issue by UserYahya** [Krinkle/mw-tool-orphantalk#9]
Thanks in advance.

**Comment by Krinkle** [comment]
Thanks for raising the issue.

**Comment by Krinkle** [comment]
Thanks for raising the issue @UserYahya.

I haven't worked on OrphanTalk for a while. I generally think of the tool as being responsive already (most of this is done automatically by Bootstrap). Here's how it looks today:

| Mobile | Desktop
|--|--
| <img width="442" alt="Screenshot 2022-12-22" src="https://user-images.githubusercontent.com/156867/209179485-ecf22f8f-d20a-4269-b7ea-48577099079a.png"> | <img width="1316" alt="Screenshot 2022-12-22" src="https://user-images.githubusercontent.com/156867/209179510-1779b37b-a209-491b-b370-26868a9e6536.png">

Can you be more specific as to what issue you are currently experiencing on mobile?

**Comment by UserYahya** [comment]
![Screenshot_20221223-155601](https://user-images.githubusercontent.com/80066484/209314799-94c80f2b-cce4-47de-865e-ccdd6d728e9b.png)
It looks like this in my case.
Browser: Chrome, version 108.0.5359.79
Device: Android 11

**Comment by Krinkle** [comment]
Exported to <https://phabricator.wikimedia.org/T331748>.
